---

- hosts: all
  become: true
  tasks:
 
  - name: update repo index
    yum:
      update_cache: yes
    when:  ansible_distribution == "CentOS"

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when:  ansible_distribution == "CentOS"

  - name: install PHP package
    yum:
      name: php
      state: latest
    when:  ansible_distribution == "CentOS"
  
  - name: update repo index
    apt:
      update_cache: yes
    when:  ansible_distribution == "Debian"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when:  ansible_distribution == "Debian"

  - name: install PHP package
    yum:
      name: libapache2-mod-php
      state: latest
    when:  ansible_distribution == "Debian"
 
  
