---

- hosts: all
  become: true
  tasks:

  - name: copy a file 
    copy:
      src: default.txt
      dest: /home/tbrown/first_ansible_copied_file
      owner: root
      group: root
      mode: 0644

- hosts: workstations
  become: true
  tasks:

  - name: install terraform
    unarchive:
       src: https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip 
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root

