---

- hosts: all
  become: true
  tasks:
 
  - name: install apache2 and php packages and update cache for CentOS
    yum:
      name: 
        - httpd
        - php
      state: latest
      #update_cache: yes
    when:  ansible_distribution == "CentOS"

  - name: install apache2 and php packages and update cache for Debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      #update_cache: yes
    when:  ansible_distribution == "Debian"

