---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates CentOS
    tags: always
    yum:
      update_only: yes
    when: ansible_distribution == "CentOS"

  - name: install updates Debian
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when:  ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  roles:
     - workstations
