---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates CentOS
    tags: always
    yum:
      update_only: yes
    when: ansible_distribution == "CentOS"

  - name: install updates Debian
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when:  ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:
 
  - name: install apache2 and php packages and update cache for CentOS
    tags: apache,httpd,centos
    yum:
      name: 
        - httpd
        - php
      state: latest
      #update_cache: yes
    when:  ansible_distribution == "CentOS"

  - name: install apache2 and php packages and update cache for Debian
    tags: apache2,ubuntu,apache
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      #update_cache: yes
    when:  ansible_distribution == "Debian"

- hosts: other_servers
  become: true
  tasks:

  - name: install mariadb Centos
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb Debian
    tags: debian,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: log_server
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest


