---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates CentOS
    yum:
      update_only: yes
      update_casche: yes
    when: ansible_distribution == "CentOS"

  - name: install updates Debian
    apt:
      upgrade: dist
      update_cache: yes
    when:  ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:
 
  - name: install apache2 and php packages for CentOS
    yum:
      name: 
        - httpd
        - php
      state: latest
      #update_cache: yes
    when:  ansible_distribution == "CentOS"

  - name: install apache2 and php packages for Debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      #update_cache: yes
    when:  ansible_distribution == "Debian"

- hosts: other_servers
  become: true
  tasks:

  - name: install mariadb Centos
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb Debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: log_server
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest


