- name: install apache2 and php packages for CentOS
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
    #update_cache: yes
  when:  ansible_distribution == "CentOS"


- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service: 
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
