 - name: install mariadb Centos
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb Debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

